### ISSUE TITLE
Cannot reach instances

### ISSUE THREAD

**Issue by guidonte** [dguerri/vagrant-ansible-openstack#17]
Hi,

I was able to run flawlessly your recipe under Virtualabox (using the 'breqwatr/trusty64' box and setting NOVA_VIRT_TYPE: "qemu"). Great work! :-)

I can't to reach running instances though. I've setup the demo project and I'm trying to ping/ssh the instance at 10.29.29.2 (with floating IP 192.168.0.101) from both my machine and the controller/network/compute nodes, with no luck. The network topology is shown in the picture 

![openstack-network-topology](https://cloud.githubusercontent.com/assets/8776774/7315413/80b11ade-ea6d-11e4-8c13-1d54aa0691e3.png)

The instance's state is:

Instance Name: demo-instance1
Image Name: cirros-0.3.3-x86_64	
IP Address: 10.29.29.2 - 192.168.0.101
Status: Running

I'm very new to Openstack and not much inside networking matters.. what am I missing?

Thank you so much for your work and any help!

**Comment by dguerri** [comment]
Confirmed.
On OSX, with VirtualBox4.3.26 instances are not reachable and they can't connect to external networks.
Parallels/LibVirt works fine, so this must be VirtualBox specific.
Instances are reachable from the network node, using the router namespace:
```bash
root@network:~# ip netns list 
qdhcp-b2215e49-5e78-4d91-951f-b81535a32c5d
qrouter-bee78255-1447-4996-a6a5-08ffe5803ebb
root@network:~# ip netns exec qrouter-bee78255-1447-4996-a6a5-08ffe5803ebb ping 10.29.29.5
PING 10.29.29.5 (10.29.29.5) 56(84) bytes of data.
64 bytes from 10.29.29.5: icmp_seq=1 ttl=64 time=5.25 ms
64 bytes from 10.29.29.5: icmp_seq=2 ttl=64 time=1.25 ms
64 bytes from 10.29.29.5: icmp_seq=3 ttl=64 time=1.09 ms
^C
--- 10.29.29.5 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2003ms
rtt min/avg/max/mdev = 1.095/2.532/5.250/1.923 ms
root@network:~# ip netns exec qrouter-bee78255-1447-4996-a6a5-08ffe5803ebb ssh 10.29.29.5 -lcirros
cirros@10.29.29.5's password: 
$ uname -a
Linux demo-instance1 3.2.0-68-virtual #102-Ubuntu SMP Tue Aug 12 22:14:39 UTC 2014 x86_64 GNU/Linux
```
Sniffing traffic on virtual/physical interfaces involved in VMs connectivity it turned out that: 
 - ARP works 
 - other protocols aren't forwarded to the network node

@guidonte what operating system are you using?

**Comment by dguerri** [comment]
Fixed ;)

BTW, it is now possible to set NOVA_VIRT_TYPE using LIBVIRT_DRIVER environment variable.

**Comment by guidonte** [comment]
I still cannot ping/ssh from the network node.

The machine running Virtualbox 4.3.26 uses Debian 7.8 wheezy with kernel 3.2.65-1+deb7u2 x86_64. I'm using 'breqwatr/trusty64' box.

Here is the output from the network node

    root@network:~# ip netns list
    qrouter-0fe68430-cb64-4a18-af74-df52dd3f4175
    qdhcp-161fa2f1-d175-4061-a3d5-4231e8b8bd8c

    root@network:~# ip netns exec qrouter-0fe68430-cb64-4a18-af74-df52dd3f4175 ping 192.168.0.101
    PING 192.168.0.101 (192.168.0.101) 56(84) bytes of data.
    From 192.168.0.101 icmp_seq=1 Destination Host Unreachable

    root@network:~# ip netns exec qrouter-0fe68430-cb64-4a18-af74-df52dd3f4175 ping 10.29.29.2
    PING 10.29.29.2 (10.29.29.2) 56(84) bytes of data.
    From 10.29.29.1 icmp_seq=1 Destination Host Unreachable

**Comment by dguerri** [comment]
You cannot ping the floating IP from there, but you should be able to reach the fixed IP assigned to VM's.
A couple of things to check:
 - (just to be sure!) fixed IP address of instance is actually 10.29.29.2 (source demo script in script/ and then issue a ```nova list```)
 - ARP is actually working: ```arp -na``` in the router NS for your tenant should show a mac address associated with instance IP: after a ping to the fixed IP address, try ```ip netns exec qrouter-0fe68430-cb64-4a18-af74-df52dd3f4175 arp -na```
 - log into the VM using noVNC (link is shown at the end of the ansible play) and:
    - try to ping VM gateway (e.g. ```ping 10.29.29.1```)   
    - try to ping some host on the Internet (e.g. ```ping 8.8.8.8```)

**Comment by dguerri** [comment]
@guidonte if possible for this test avoid using a WiFi interface as the external interface. I have been unable to make VM's reaching the Internet using a WiFi NIC.

Also make sure VirtualBox has correctly enabled promiscuous mode for the 4th NIC. This is done by the code added with 3ab8ec938765c520aed9090baa3ee7a4447f8ae7

![screen shot 2015-04-24 at 1 10 21 pm](https://cloud.githubusercontent.com/assets/509264/7318389/5c17ee4e-ea83-11e4-85fe-22657a558d01.png)

**Comment by guidonte** [comment]
I'm using an Ethernet interface as external one. Actually I'm running on a server of my company's - so no VirtualBox GUI there :-/

    $ VBoxManage showvminfo vagrant-ansible-openstack_network_1429788201568_8290 | grep "NIC 4"
    NIC 4:           MAC: 080027A80E13, Attachment: Bridged Interface 'ypsbridge', Cable connected: on, Trace: off (file: none), Type: 82540EM, Reported speed: 0 Mbps, Boot priority: 0, Promisc Policy: allow-all, Bandwidth group: none

Requested checks:

    $ nova list
    +--------------------------------------+----------------+--------+------------+-------------+------------------------------------+
    | ID                                   | Name           | Status | Task State | Power State | Networks                           |
    +--------------------------------------+----------------+--------+------------+-------------+------------------------------------+
    | a785b4eb-0ec7-42d9-bc0b-42d15f5b37b5 | demo-instance1 | ACTIVE | -          | Running     | demo-net=10.29.29.2, 192.168.0.101 |
    +--------------------------------------+----------------+--------+------------+-------------+------------------------------------+

then from the network node:

    root@network:~# ip netns exec qrouter-0fe68430-cb64-4a18-af74-df52dd3f4175 ping 10.29.29.2
    PING 10.29.29.2 (10.29.29.2) 56(84) bytes of data.
    From 10.29.29.1 icmp_seq=1 Destination Host Unreachable

    root@network:~# ip netns exec qrouter-0fe68430-cb64-4a18-af74-df52dd3f4175 arp -na
    ? (10.29.29.2) at <incomplete> on qr-29549d91-68
    ? (10.29.29.5) at <incomplete> on qr-29549d91-68

As I'm running on remote server, I've set up port forwarding for the controller node, like this:

    server.vm.network "forwarded_port", guest: 6080, host: 6080

but I get en error from noNVC when opening the link "Failed to connect to server (code: 1006)"

**Comment by guidonte** [comment]
here you find the boot log of the running instance http://pastebin.com/GRUfc0uj

**Comment by dguerri** [comment]
Damn, I cannot reproduce it now.

So it boots correctly but the boot log shows that something went wrong. 
Specifically, that instance couldn't get an IP address via DHCP
```
Starting network...
udhcpc (v1.20.1) started
Sending discover...
Sending discover...
Sending discover...
Usage: /sbin/cirros-dhcpc <up|down>
No lease, failing
WARN: /etc/rc3.d/S40-network failed
```

This is the boot log for a working instance.
http://paste.openstack.org/show/205669/

On the server running virtual box make sure no iptables rules are in the way. Then check connectivity between compute nodes and the network node:
```ping 192.168.129.7``` and try to sniff eth2 on compute* and network nodes to check GRE traffic is flowing during instance boot.

Also, check services logs on network and compute nodes, especially those related to neutron.

**Comment by guidonte** [comment]
I'll sure try that next week when I'm back to work, thanks for your help!

**Comment by retr0h** [comment]
@guidonte I have similar problems with VB.  I have never been successful in reaching the floating address, but it should be possible.

**Comment by dguerri** [comment]
hey @retr0h ! 
If you could please try the current master HEAD it would be great.
It turned out that with VB needs to have the external interface in promiscuous mode (see 3ab8ec938765c520aed9090baa3ee7a4447f8ae7)

**Comment by retr0h** [comment]
Hi @dguerri - No luck for me.  I've never been able to figure out how to ping the floating IP from my mac with VirtualBox.

```
(.venv)JODEWEY-M-D0YN:vagrant-ansible-openstack% ping 192.168.0.101
PING 192.168.0.101 (192.168.0.101): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
```
```
root@network:~# ip netns exec qrouter-eb0e7a08-9e3b-4add-8058-bbddcdf558ef ping 10.29.29.6
PING 10.29.29.6 (10.29.29.6) 56(84) bytes of data.
64 bytes from 10.29.29.6: icmp_seq=1 ttl=64 time=4.50 ms
64 bytes from 10.29.29.6: icmp_seq=2 ttl=64 time=2.20 ms
```

```
| a2706c30-0adc-4e9f-8ef6-edef8411f590 | demo-instance1 | ACTIVE | -          | Running     | demo-net=10.29.29.6, 192.168.0.101 |
```
```
(.venv)JODEWEY-M-D0YN:vagrant-ansible-openstack% VBoxManage showvminfo vagrant-ansible-openstack_network_1429984511802_47118 | grep "NIC 4"
NIC 4:           MAC: 080027A7CFA0, Attachment: Bridged Interface 'en0: Wi-Fi (AirPort)', Cable connected: on, Trace: off (file: none), Type: 82540EM, Reported speed: 0 Mbps, Boot priority: 0, Promisc Policy: allow-all, Bandwidth group: none
```

**Comment by dguerri** [comment]
Damn...
At least you can ping the fixed address, so your VM is correctly configured.
This issue seems different from the one @guidonte is having. It could be related to Airport card HW acceleration. I have been unable to make Parallels and VirtualBox working bridging the external interface of the ```network``` node to the airport card.
I understand your Airport card is en0... so you probably don't have a ethernet interface :(

You could try to change https://github.com/dguerri/vagrant-ansible-openstack/blob/master/Vagrantfile#L109-L111 to use a private network (like the other interfaces) with an address in https://github.com/dguerri/vagrant-ansible-openstack/blob/master/demo/group_vars/all.yml#L10-L13

and remove https://github.com/dguerri/vagrant-ansible-openstack/blob/master/Vagrantfile#L120-L122

Of course you won't be able to reach the Internet from your instances, but you should be able to reach them form your Mac.

**Comment by guidonte** [comment]
@dguerri So I tried re-creating from scratch the Vagrant environment, and now it works! I can reach instances from the network node using something like:

    $ ip netns exec qrouter-[ROUTER-ID] ping 10.29.29.2
    $ ip netns exec qrouter-[ROUTER-ID] ssh cirros@10.29.29.2

Probably there was some misconfiguration related to the setup done before the Virtualbox inferface promiscuous mode change. Just guessing though...

**Comment by dguerri** [comment]
@guidonte good to hear you managed to get it working. :+1: 
Is your floatingIP reachable as well?

**Comment by guidonte** [comment]
@dguerri yes I can reach the floating IP too!

**Comment by dguerri** [comment]
:beers:

**Comment by guidonte** [comment]
is it possible now to reach the instances from outside the network node, that is directly from the vagrant workstation?

**Comment by guidonte** [comment]
you may want to pull in some README.md changes https://github.com/guidonte/vagrant-ansible-openstack/tree/readme-tweaks

**Comment by dguerri** [comment]
> is it possible now to reach the instances from outside the network node, that is directly from the vagrant workstation?

It should be, as long as you have a consistent addressing (i.e. floating IP in in a subnet used by other systems on the bridged L2)

> you may want to pull in some README.md changes https://github.com/guidonte/vagrant-ansible-openstack/tree/readme-tweaks

Brilliant. Can you please add a section named "Debugging" (or something similar) with those instructions?
Don't submit another commit, just amend that one and push --force to your repo (PR will update automagically)

**Comment by guidonte** [comment]
done, thanks!

**Comment by dguerri** [comment]
Please submit a PR, I will merge it straight away.

**Comment by dguerri** [comment]
I am going to close this bug report.
We are aware of an issue with airport (and possibly others) WiFi cards with Parallels/VirtualBox. Nevertheless, there is nothing we can do here!
